-- NOTE: This migration is superseded by 20260101_init which creates
-- UserStreak and UserAchievement as part of the full initial schema.
-- This file is kept for historical reference only.
-- On a fresh database, run 20260101_init instead.
